/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-05-22 02:45:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jquery;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class test4_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"../js/jquery-3.7.0.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	$(function() {\r\n");
      out.write("		/*\r\n");
      out.write("		css() 함수\r\n");
      out.write("		- 파라미터로 속성명 지정 시 해당 CSS 속성값 리턴\r\n");
      out.write("		  => 이 때, 대상이 복수개일 경우 첫번째 요소의 값만 리턴\r\n");
      out.write("		- 속성명과 속성값 함께 지정 시 해당 CSS 속성값 변경\r\n");
      out.write("		  => 이 때, 대상이 복수개일 경우 복수개의 모든 요소 값 변경\r\n");
      out.write("		*/\r\n");
      out.write("		\r\n");
      out.write("		// h3 태그의 \"color\" 속성값 출력\r\n");
      out.write("// 		alert($(\"h3\").css(\"color\")); // rgb(0, 0, 0)\r\n");
      out.write("		\r\n");
      out.write("		// 모든 h3 태그의 \"color\" 속성값을 \"green\" 으로 변경\r\n");
      out.write("		$(\"h3\").css(\"color\", \"green\");\r\n");
      out.write("		\r\n");
      out.write("		// 첫번째 h3 태그의 \"color\" 속성값만 \"blue\" 로 변경\r\n");
      out.write("		// => 순서선택자 :first 사용 가능\r\n");
      out.write("		$(\"h3:first\").css(\"color\", \"blue\");\r\n");
      out.write("		\r\n");
      out.write("		// h3 태그의 \"color\" 속성값 출력\r\n");
      out.write("// 		alert($(\"h3\").css(\"color\")); // rgb(0, 0, 255) = blue 출력됨\r\n");
      out.write("		// => 첫번째 h3 태그의 color 속성값 리턴하므로 blue 만 출력됨\r\n");
      out.write("		\r\n");
      out.write("		/*\r\n");
      out.write("		css() 함수(다른 함수도 가능)내에서 익명함수 구현 시\r\n");
      out.write("	 	대상 태그를 차례대로 접근하는 반복문 형태로 사용 가능함\r\n");
      out.write("	 	=> css(\"속성명\", function([파라미터...]) {})\r\n");
      out.write("	 	=> css(\"속성명\", function() {})\r\n");
      out.write("	 	=> css(\"속성명\", function(index) {})\r\n");
      out.write("	 	=> css(\"속성명\", function(index, value) {})\r\n");
      out.write("		*/\r\n");
      out.write("		// 1) 파라미터가 없는 익명함수 구현 시 해당 태그 갯수만큼 반복 수행함\r\n");
      out.write("		//    => css(\"속성명\", function() {})\r\n");
      out.write("		$(\"h3\").css(\"color\", function() {\r\n");
      out.write("			console.log(\"h3 태그 접근!\"); // 3번 실행됨(h3 태그가 3개)\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		// 2) 파라미터가 1개인 익명함수 구현 시 해당 태그 갯수만큼 반복 수행하면서\r\n");
      out.write("		//    현재 태그의 인덱스(순서번호)가 리턴됨(파라미터(변수)에 저장됨)\r\n");
      out.write("		//    => css(\"속성명\", function(index) {})\r\n");
      out.write("		$(\"h3\").css(\"color\", function(index) {\r\n");
      out.write("			console.log(index + \"번 h3 태그 접근!\");\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		// 3) 파라미터가 2개인 익명함수 구현 시 해당 태그 갯수만큼 반복 수행하면서\r\n");
      out.write("		//    현재 태그의 인덱스와 속성값이 리턴됨(파라미터(변수)에 저장됨)\r\n");
      out.write("		//    => css(\"속성명\", function(index, value) {})\r\n");
      out.write("		$(\"h3\").css(\"color\", function(index, value) {\r\n");
      out.write("			console.log(index + \"번 h3 태그 color 속성값 : \" + value);\r\n");
      out.write("			// 0번 h3 태그 color 속성값 : rgb(0, 0, 255)\r\n");
      out.write("			// 1번 h3 태그 color 속성값 : rgb(0, 128, 0)\r\n");
      out.write("			// 2번 h3 태그 color 속성값 : rgb(0, 128, 0)\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		// --------------------------------------------------------------------\r\n");
      out.write("		// 배열을 활용하면 대상 태그 속성값을 차례대로 한꺼번에 변경도 가능\r\n");
      out.write("		// => 대상을 반복하면서 값 변경 시 return 문을 통해 변경할 값을 리턴\r\n");
      out.write("		\r\n");
      out.write("		// 변경에 사용될 속성값을 각 배열에 저장\r\n");
      out.write("		let colorValue = [\"red\", \"green\", \"blue\"];\r\n");
      out.write("		let bgColorValue = [\"cyan\", \"skyblue\", \"yellow\"];\r\n");
      out.write("		\r\n");
      out.write("		// h3 태그의 css 함수를 호출하여 \"color\" 속성에 차례대로 접근 반복(인덱스 리턴받기)\r\n");
      out.write("// 		$(\"h3\").css(\"color\", function(index) {\r\n");
      out.write("// // 			return \"red\"; // 반복하는 대상의 모든 color 속성값을 \"red\" 로 변경\r\n");
      out.write("			\r\n");
      out.write("// 			// 함수 파라미터로 전달받는 index 값을 배열 인덱스로 활용하여 속성값 리턴\r\n");
      out.write("// 			return colorValue[index];\r\n");
      out.write("// 		});\r\n");
      out.write("		\r\n");
      out.write("		// h3 태그의 css 함수를 호출하여 \"background\" 속성에 차례대로 접근 반복(인덱스 리턴받기)\r\n");
      out.write("		// => bgColorValue 배열 활용하여 배경색 변경\r\n");
      out.write("// 		$(\"h3\").css(\"background\", function(index) {\r\n");
      out.write("// 			return bgColorValue[index];\r\n");
      out.write("// 		});\r\n");
      out.write("		\r\n");
      out.write("		// 동일한 대상에 동일한 함수로 복수개의 속성을 반복문 형태로 변경하는 경우\r\n");
      out.write("		// $(\"선택자\").css({속성1:함수(index){}, 속성2:함수(index){}});\r\n");
      out.write("		$(\"h3\").css({\r\n");
      out.write("			color: function(index) {\r\n");
      out.write("				return colorValue[index];\r\n");
      out.write("			},\r\n");
      out.write("			background: function(index) {\r\n");
      out.write("				return bgColorValue[index];\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<h1>jQuery - test4.jsp</h1>\r\n");
      out.write("	<h3>제목1</h3>\r\n");
      out.write("	<h3>제목2</h3>\r\n");
      out.write("	<h3>제목3</h3>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
