/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-05-23 02:15:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jquery;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class test9_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"../js/jquery-3.7.0.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	/*\r\n");
      out.write("	DOM 객체(요소)를 탐색 및 접근하여 대상을 조작하는 방법\r\n");
      out.write("	- HTML 태그에 대한 자바스크립트 이벤트와 동일함\r\n");
      out.write("	- 대상 요소 지정하여 이벤트 처리를 수행하는 각각의 메서드를 호출하거나\r\n");
      out.write("	  (ex. click(), submit() 메서드 등)\r\n");
      out.write("	  on() 메서드 내에 이벤트 이름을 지정하여 각각의 이벤트를 처리 가능\r\n");
      out.write("	  (ex. on(\"click\"), on(\"submit\") 등)\r\n");
      out.write("	\r\n");
      out.write("	1. on(\"click\") 메서드\r\n");
      out.write("	   - 특정 대상을 \"클릭\" 시 동작하는 이벤트 처리(click() 메서드와 동일)\r\n");
      out.write("	   - 클릭 대상에 대한 제한 없음(버튼이 아닌 요소도 가능)\r\n");
      out.write("	\r\n");
      out.write("	2. on(\"focus\") 또는 on(\"blur\") 메서드\r\n");
      out.write("	   - 특정 대상에 포커스가 주어지거나 해제 시 동작하는 이벤트 처리\r\n");
      out.write("	   - focus(), blue() 메서드와 동일\r\n");
      out.write("	   - 클릭이 아닌 키보드 등을 통한 포커스 이동도 동일하게 취급됨\r\n");
      out.write("	*/\r\n");
      out.write("	$(function() {\r\n");
      out.write("		// 확인 버튼 클릭 시 버튼의 value 값 가져와서 출력하기\r\n");
      out.write("// 		alert($(\"input[type=button]\").eq(0).val());\r\n");
      out.write("		\r\n");
      out.write("		// 확인 버튼 클릭 시 메세지 출력\r\n");
      out.write("// 		$(\"input[type=button]\").eq(0).on(\"click\", function() {\r\n");
      out.write("// 			alert(\"확인 버튼 클릭!\");\r\n");
      out.write("// 		});\r\n");
      out.write("		\r\n");
      out.write("		// 취소 버튼 클릭 시 메세지 출력\r\n");
      out.write("// 		$(\"input[type=button]\").eq(1).on(\"click\", function() {\r\n");
      out.write("// 			alert(\"취소 버튼 클릭!\");\r\n");
      out.write("// 		});\r\n");
      out.write("		\r\n");
      out.write("		// -------------------------------------------------------\r\n");
      out.write("		// 버튼을 지정하는 선택자로 가상선택자 \":button\" 사용 가능\r\n");
      out.write("// 		$(\":button\").on(\"click\", function() {\r\n");
      out.write("// // 			alert(\"버튼 클릭!\");\r\n");
      out.write("// // 			alert($(this).val()); // 클릭된 버튼을 $(this) 로 가리킴(버튼 텍스트 출력)\r\n");
      out.write("// 			// 확인 or 취소 버튼 판별\r\n");
      out.write("// 			if($(this).val() == \"확인\") {\r\n");
      out.write("// 				alert(\"확인!\");\r\n");
      out.write("// 			} else {\r\n");
      out.write("// 				alert(\"취소!\");\r\n");
      out.write("// 			}\r\n");
      out.write("// 		});\r\n");
      out.write("		// -------------------------------------------------------\r\n");
      out.write("		// 확인 버튼(= 첫번째 버튼) 클릭되면 익명 함수 실행\r\n");
      out.write("		$(\":button\").eq(0).on(\"click\", function() {\r\n");
      out.write("			// 입력받은 아이디, 패스워드, 선택된 과목명을 textarea 에 출력\r\n");
      out.write("			// => val() 메서드 또는 html(), text() 메서드 활용\r\n");
      out.write("			// => 셀렉트박스는 $(\"선택자\").val() 을 통해 셀렉트박스의 값을 가져오거나\r\n");
      out.write("			//    $(\"선택자 > option:selected\").val() 을 통해 옵션 중 선택된 요소 값 가져오기 가능 \r\n");
      out.write("			$(\"#resultArea\").html(\r\n");
      out.write("				\"아이디 : \" + $(\"input[name=id]\").val()	+ \"\\n\"\r\n");
      out.write("				+ \"패스워드 : \" + $(\"input[name=passwd]\").val()	+ \"\\n\"\r\n");
      out.write("				+ \"선택과목 : \" + $(\"#selectBox\").val()	+ \"\\n\"\r\n");
      out.write("				+ \"선택과목 : \" + $(\"#selectBox > option:selected\").val()	+ \"\\n\"\r\n");
      out.write("			);\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("// 		$(\"textarea\").on(\"click\", function() {\r\n");
      out.write("// 			alert(\"textarea 클릭!\");\r\n");
      out.write("// 		});\r\n");
      out.write("		\r\n");
      out.write("		// div 영역(\"clickDiv\") 클릭 이벤트\r\n");
      out.write("		$(\"#clickDiv\").on(\"click\", function() {\r\n");
      out.write("			alert(\"div 클릭!\");\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		// textarea focus, blur 이벤트 처리\r\n");
      out.write("		$(\"#resultArea\").on(\"focus\", function() {\r\n");
      out.write("			$(\"#resultArea\").html(\"textarea focus in\");\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		$(\"#resultArea\").on(\"blur\", function() {\r\n");
      out.write("			$(\"#resultArea\").html(\"textarea focus out\");\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<h1>jQuery - test9.jsp</h1>\r\n");
      out.write("	<div id=\"wrap\">\r\n");
      out.write("		<div id=\"inputBox\">\r\n");
      out.write("			아이디 : <input type=\"text\" name=\"id\"><br>\r\n");
      out.write("			패스워드 : <input type=\"password\" name=\"passwd\"><br>\r\n");
      out.write("			<select id=\"selectBox\" name=\"subject\">\r\n");
      out.write("				<option value=\"\">선택하세요</option>\r\n");
      out.write("				<option value=\"자바\">자바</option>\r\n");
      out.write("				<option value=\"JSP\">JSP</option>\r\n");
      out.write("				<option value=\"스프링\">스프링</option>\r\n");
      out.write("			</select>\r\n");
      out.write("		</div>\r\n");
      out.write("		<textarea rows=\"5\" cols=\"20\" id=\"resultArea\"></textarea>\r\n");
      out.write("		<br>\r\n");
      out.write("		<input type=\"button\" value=\"확인\">\r\n");
      out.write("		<input type=\"button\" value=\"취소\">\r\n");
      out.write("	</div>\r\n");
      out.write("	<br>\r\n");
      out.write("	-----------\r\n");
      out.write("	<div id=\"clickDiv\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div>\r\n");
      out.write("	-----------\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
